=== hmis-api/2014-hmis-api/api-markup/types/exit.json
{
"$schema": "http://json-schema.org/draft-04/schema",
"title": "exit",
"type": "object",
"$schema": "http://json-schema.org/draft-04/schema",
  "required":["ExitID","ProjectEntryID","DateCreated","ExitDate","DateUpdated","UserID"],
"properties": {
  "ExitID": {
    "type": "string",
    "maxLength": 32,
    "minLength": 32
  },
  "ProjectEntryID": {
    "type": "string",
    "maxLength": 32,
    "minLength": 32
  },
  "ExitDate": {
    "type": "string",
    "format": "date-time"
  },
  "Destination": {
    "type": "integer"
  },
  "OtherDestination": {
    "type": "string",
    "maxLength": 50
  },
  "DateCreated": {
    "type": "string",
    "format": "date-time"
  },
  "DateUpdated": {
    "type": "string",
    "format": "date-time"
  },
  "DateDeleted": {
    "type": "string",
    "format": "date-time"
  },
  "UserID": {
    "type": "string",
    "maxLength": 32,
    "minLength": 32}
  }
}

=== hmis-api/2014-hmis-api/api-markup/examples/put_exit_json_req.json
{
  "ExitID":"9d57c33f-cc4e-47ff-8bbd-0580e7a0",
  "ProjectEntryID":"9d57c33f-cc4e-47ff-8bbd-0580e7a0",
  "ExitDate":"1997-07-16T19:20:30.45+01:00",
  "Destination":24,
  "OtherDestination":"Test destination",
  "DateCreated":"1997-07-16T19:20:30.45+01:00",
  "DateUpdated":"1997-07-16T19:20:30.45+01:00",
  "DateDeleted":"1997-07-16T19:20:30.45+01:00",
  "UserID":"9d57c33f-cc4e-47ff-8bbd-0580e7a0"
}
